export const myVocaPairs = [
  ["create", "chế tạo"],
  ["way", "cách, đường"],
  ["celebration", "kỉ niệm"],
  ["ingredient", "nguyên liệu"],
  ["flour", "bột mì"],
  ["butter", "bơ"],
  ["sugar", "đường"],
  ["egg", "trứng"],
  ["baking powder", "bột nở"],
  ["extract", "triết xuất"],
  ["preheat", "làm nóng"],
  ["the oven", "lò"],
  ["start by", "bắt đầu bằng"],
  ["delicious", "ngon"],
  ["allow", "cho phép"],
  ["mixing", "trộn"],
  ["batter", "hỗn hợp"],
  ["bowl", "tô"],
  ["tookick", "tăm, que"],
  ["bake", "nướng"],
  ["light", "ánh sáng"],
  ["fluffy", "mịn"],
  ["until", "cho tới khi"],
  ["pour", "đổ"],
  ["prepare", "chuẩn bị"],
  ["insert", "đặt vào, chèn vào"],
  ["spread", "phết..."],
  ["decorate", "trang trí"],
  ["frirting", "tán tỉnh"],
  ["tips", "những lời khuyên"],
  ["here are", "đây là"],
  ["celebrity", "người nổi tiếng"],
  ["wonderful", "tuyệt vời"],
  ["genuine", "chân thành"],
  ["exciting", "thú vị"],
  ["fun", "vui"],
  ["humorous", "hài hước"],
  ["laugh", "cười"],
  ["cough", "ho"],
  ["interest", "quan tâm"],
  ["ask", "hỏi"],
  ["feel", "cảm giác"],
  ["connect", "kết nối"],
  ["contact", "giao tiếp"],
  ["enjoying", "tận hưởng"],
  ["friendly", "thân thiện"],
  ["compliment", "lời khuyên"],
  ["actively listening", "lắng nghe chăm chú"],
  ["confident", "tự tin"],
  ["let your personality shine", "hãy để bản thân bạn được toả sáng"],
  ["positive", "tích cực"],
  ["excellent", "xuất xắc"],
  ["degree", "bằng cấp"],
  ["company", "công ty"],
  ["introduce", "giới thiệu"],
  ["most of them", "hầu hết bọn họ"],
  ["apply to, supply", "nộp đơn..."],
  ["experiment", "thí nghiệm"],
  ["experience", "trải nghiệm"],
  ["service", "dịch vụ"],
  ["refuse", "từ chối"],
  ["accept", "chấp nhận"],
  ["salary", "lương"],
  ["merit", "công lao"],
  ["granduate", "tốt nghiệp"],
  ["there might be", "có thể có"],
  ["interview", "phỏng vấn"],
  ["unforntunately", "xuôi xẻo thay"],
  ["exactly", "chính xác"],
  ["enthusiast", "niềm đam mê"],
  ["early", "gần"],
  ["routine", "thói quen"],
  ["daily", "hằng ngày"],
  ["mothly", "hằng tháng"],
  ["annually", "hằng năm"],
  ["there might ", "chẳng hề"],
  ["pain", "đau"],
  ["customer", "khách hàng"],
  ["serious", "nghiêm trọng"],
  ["emergency", "khẩn cấp"],
  ["near", "gần"],
  ["turn", "biến, quay"],
  ["speacially", "đặc biệt"],
  ["mystery", "bí ẩn"],
  ["please not", "xin hãy chú ý"],
  ["imaginate", "giả tưởng"],
  ["progress well", "tiến triển tốt"],
  ["base", "dựa trên"],
  ["his spirit leaf his body", "thần rời khỏi xác"],
  ["neighbor", "hàng xóm"],
  ["giving birth", "việc đẻ, sinh,..."],
  ["average", "trung bình"],
  ["ginger", "gừng"],
  ["up to", "lên tới"],
  ["date", "hẹn hò, ngày"],
  ["visit", "thăm"],
  ["lazy", "lười"],
  ["receive", "nhận"],
  ["any", "bất kì"],
  ["nearly", "gần"],
];

export const wordsPerDay = 7;

